### PR TITLE
fix: update redpanda, fix issues

### LINKED ISSUE #169: redpanda frame read errors with early eof
rskafka fails to read frames when talking to the latest redpanda release ([v22.2.1](https://github.com/redpanda-data/redpanda/releases/tag/v22.2.1)). It is unclear if this is a redpanda bug, or rskafka - I can't see any reports in the redpanda issue tracker, and rskafka doesn't progress at all, so I suspect it is us as redpanda would quickly have issues filed if it didn't work at all!

Log snippet from the IOx tests where I discovered the problem:

```
2022-08-19T15:49:53.188690Z  INFO rskafka::connection: Establishing new connection url="127.0.0.1:52575"
2022-08-19T15:49:53.194054Z  WARN rskafka::connection: Failed to connect to broker e=cannot sync versions: Request error: Connection is poisoned: Cannot read framed message: Cannot read data: early eof
2022-08-19T15:49:53.194124Z  INFO rskafka::backoff: request encountered non-fatal error - backing off e=Failed to connect to any broker, backing off request_name="broker_connect" backoff_secs=0
2022-08-19T15:49:53.296358Z  INFO rskafka::connection: Establishing new connection url="127.0.0.1:52575"
2022-08-19T15:49:53.300379Z  WARN rskafka::connection: Failed to connect to broker e=cannot sync versions: Request error: Connection is poisoned: Cannot read framed message: Cannot read data: early eof
2022-08-19T15:49:53.300421Z  INFO rskafka::backoff: request encountered non-fatal error - backing off e=Failed to connect to any broker, backing off request_name="broker_connect" backoff_secs=0
2022-08-19T15:49:53.489981Z  INFO rskafka::connection: Establishing new connection url="127.0.0.1:52575"
2022-08-19T15:49:53.499777Z  WARN rskafka::connection: Failed to connect to broker e=cannot sync versions: Request error: Connection is poisoned: Cannot read framed message: Cannot read data: early eof
2022-08-19T15:49:53.499963Z  INFO rskafka::backoff: request encountered non-fatal error - backing off e=Failed to connect to any broker, backing off request_name="broker_connect" backoff_secs=0
2022-08-19T15:49:53.631317Z  INFO rskafka::connection: Establishing new connection url="127.0.0.1:52575"
2022-08-19T15:49:53.642401Z  WARN rskafka::connection: Failed to connect to broker e=cannot sync versions: Request error: Connection is poisoned: Cannot read framed message: Cannot read data: early eof
2022-08-19T15:49:53.642451Z  INFO rskafka::backoff: request encountered non-fatal error - backing off e=Failed to connect to any broker, backing off request_name="broker_connect" backoff_secs=0
2022-08-19T15:49:54.026461Z  INFO rskafka::connection: Establishing new connection url="127.0.0.1:52575"
2022-08-19T15:49:54.037168Z  WARN rskafka::connection: Failed to connect to broker e=cannot sync versions: Request error: Connection is poisoned: Cannot read framed message: Cannot read data: early eof
2022-08-19T15:49:54.037317Z  INFO rskafka::backoff: request encountered non-fatal error - backing off e=Failed to connect to any broker, backing off request_name="broker_connect" backoff_secs=0
2022-08-19T15:49:54.372955Z  INFO rskafka::connection: Establishing new connection url="127.0.0.1:52575"
2022-08-19T15:49:54.383209Z  WARN rskafka::connection: Failed to connect to broker e=cannot sync versions: Request error: Connection is poisoned: Cannot read framed message: Cannot read data: early eof
2022-08-19T15:49:54.383369Z  INFO rskafka::backoff: request encountered non-fatal error - backing off e=Failed to connect to any broker, backing off request_name="broker_connect" backoff_secs=0
2022-08-19T15:49:54.570851Z  INFO rskafka::connection: Establishing new connection url="127.0.0.1:52575"
2022-08-19T15:49:54.584100Z  WARN rskafka::connection: Failed to connect to broker e=cannot sync versions: Request error: Connection is poisoned: Cannot read framed message: Cannot read data: early eof
2022-08-19T15:49:54.584243Z  INFO rskafka::backoff: request encountered non-fatal error - backing off e=Failed to connect to any broker, backing off request_name="broker_connect" backoff_secs=0
2022-08-19T15:49:54.726602Z  INFO rskafka::connection: Establishing new connection url="127.0.0.1:52575"
2022-08-19T15:49:54.740463Z  WARN rskafka::connection: Failed to connect to broker e=cannot sync versions: Request error: Connection is poisoned: Cannot read framed message: Cannot read data: early eof
2022-08-19T15:49:54.740640Z  INFO rskafka::backoff: request encountered non-fatal error - backing off e=Failed to connect to any broker, backing off request_name="broker_connect" backoff_secs=0
2022-08-19T15:49:55.092203Z  INFO rskafka::connection: Establishing new connection url="127.0.0.1:52575"
2022-08-19T15:49:55.113559Z  WARN rskafka::connection: Failed to connect to broker e=cannot sync versions: Request error: Connection is poisoned: Cannot read framed message: Cannot read data: early eof
2022-08-19T15:49:55.113719Z  INFO rskafka::backoff: request encountered non-fatal error - backing off e=Failed to connect to any broker, backing off request_name="broker_connect" backoff_secs=0
2022-08-19T15:49:55.822818Z  INFO rskafka::connection: Establishing new connection url="127.0.0.1:52575"
2022-08-19T15:49:55.836358Z  WARN rskafka::connection: Failed to connect to broker e=cannot sync versions: Request error: Connection is poisoned: Cannot read framed message: Cannot read data: early eof
2022-08-19T15:49:55.836520Z  INFO rskafka::backoff: request encountered non-fatal error - backing off e=Failed to connect to any broker, backing off request_name="broker_connect" backoff_secs=0
2022-08-19T15:49:56.760850Z  INFO rskafka::connection: Establishing new connection url="127.0.0.1:52575"
2022-08-19T15:49:56.770216Z  WARN rskafka::connection: Failed to connect to broker e=cannot sync versions: Request error: Connection is poisoned: Cannot read framed message: Cannot read data: early eof
2022-08-19T15:49:56.770301Z  INFO rskafka::backoff: request encountered non-fatal error - backing off e=Failed to connect to any broker, backing off request_name="broker_connect" backoff_secs=2
```

See #168.

### PR DESCRIPTION
**Pull request by crepererum**
# 1. Protocol "Fix"
Redpanda seems to expect that we send a bit more data in the protocol header (kafka doesn't care), so let's make it happy.

# 2. Topic-auto-creation
Topic auto-creation should never have worked for our dev/ci Kafka/redpanda nodes. Let's disable it (this actually was caught by the test for the bind mode feature, see next point).

# 3. Bind mode to address "unknown topic or partition"
Let's face it: the protocol is a bit of a mess and some users (mostly
the ones that expect that partitions can be deleted) need to deal with
it, while for others we can make iron over it.

Closes #168.
Fixes #169.

### CODE REVIEW

File: src/client/partition.rs [hunk 1]
```diff
@@ -32,8 +32,40 @@ use tracing::{error, info};
 
 use super::error::ServerErrorResponse;
 
+/// How strongly a [`PartitionClient`] is bound to a partition.
+///
+/// Under some circumstances and broker implementations, you might face a [`ProtocolError::UnknownTopicOrPartition`]
+/// for nearly all operations directly after topic/partition creation. Since the Kafka protocol offers no (at least
+/// to our knowledge) we to differentiate between "a topic/partition actually does not exist" and "our multiverse
```
Comment (domodwyer) [inline src/client/partition.rs:39]:
```suggestion
/// to our knowledge) way to differentiate between "a topic/partition actually does not exist" and "our multiverse
```

File: src/client/partition.rs [hunk 2]
```diff
@@ -32,8 +32,40 @@ use tracing::{error, info};
...
+/// split brain is not synced up yet", we can only offer your this manual way to wait for the existence.
```
Comment (domodwyer) [inline src/client/partition.rs:40]:
```suggestion
/// split brain is not synced up yet", we can only offer you a manual way to wait for topic existence.
```

File: src/client/partition.rs [hunk 3]
```diff
@@ -32,8 +32,40 @@ use tracing::{error, info};
...
+    /// Assume that the partition (or topic that contains it) can be deleted at any time.
+    ///
+    /// This bubbles [`ProtocolError::UnknownTopicOrPartition`] to the user.
+    Weak,
+
+    /// Assume that the partition (and topic that contais it) exist.
+    ///
+    /// This retries [`ProtocolError::UnknownTopicOrPartition`].
+    Strong,
+}
```
Comment (domodwyer) [inline src/client/partition.rs:58]: I find the `bind_mode` / `PartitionClientBindMode::Strong` (and weak) naming to be quite disconnected from the underlying behaviour they control - what about something like:

```suggestion
pub enum UnknownTopicHandling {
    /// When a [`ProtocolError::UnknownTopicOrPartition`] is returned by Kafka,
    /// it is passed up to the user to handle.
    ///
    /// These errors may occur spuriously.
    Error,

    /// Always retry operations that return a
    /// [`ProtocolError::UnknownTopicOrPartition`], until the operation succeeds
    /// or a different error is returned.
    ///
    /// This may unpredictably increase operation latency.
    Retry,
}
```

File: src/messenger.rs [hunk 4]
```diff
@@ -302,7 +302,9 @@ where
             request_api_key: R::API_KEY,
             request_api_version: body_api_version,
             correlation_id: Int32(correlation_id),
-            client_id: Some(NullableString(None)),
+            // Technically we don't need to send a client_id, but newer redpanda version fail to parse the message
+            // without it. See https://github.com/influxdata/rskafka/issues/169 .
+            client_id: Some(NullableString(Some(String::from(env!("CARGO_PKG_NAME"))))),
```
Comment (domodwyer) [inline src/messenger.rs:307]: Just to confirm, is this the fix for the redpanda problem (https://github.com/influxdata/rskafka/issues/169)? 

And the rest of this PR is unrelated to the compatibility problem, but helps eliminate the topic existence (or lack off) we see in testing?

File: src/client/partition.rs [hunk 5]
```diff
@@ -435,6 +486,12 @@ where
                 } => {
                     broker_cache.invalidate().await;
                 }
+                Error::ServerError {
+                    protocol_error: ProtocolError::UnknownTopicOrPartition,
+                    ..
+                } if bind_mode == PartitionClientBindMode::Strong => {
+                    broker_cache.invalidate().await;
+                }
```
Comment (domodwyer) [inline src/client/partition.rs:494]: Why would we not invalidate the cache for the "weak/error" mode of operation?

**Review by domodwyer — COMMENTED** [review]
Few questions to understand the changes rather than comments on the code.

File: src/client/partition.rs (hunk 5 above)
Comment (crepererum) [reply src/client/partition.rs]: done

File: src/client/partition.rs (hunk 3 above)
Comment (crepererum) [reply src/client/partition.rs]: done

**Comment by crepererum** [comment]
@domodwyer ready for round 2

**Review by domodwyer — APPROVED** [review]
Top detective work! 🚢
