### PR TITLE
fix: make `Messenger::request` cancellation-safe

### LINKED ISSUE #103: Frequent connection losses
On the producer side, we see loads (~once per minute) connection losses in prod, like:

`level=info msg="request encountered non-fatal error - backing off" e="Request error: Connection is poisened: Cannot read framed message: Cannot read data: early eof" request_name=produce backoff_secs=0 target="rskafka::backoff"`

They are automatically retried, but it would be nice if we could prevent this from happening THAT often.

### PR DESCRIPTION
**Pull request by crepererum**
This avoids that we write partial messages to the underlying TCP/TLS
connection and mess up message framing. This will nearly always lead to
broker-side errors and the broker closes the connection.

Fixes #103.

### CODE REVIEW

File: src/messenger.rs [hunk 1]
```diff
@@ -922,6 +932,122 @@ mod tests {
         assert_eq!(actual, resp);
     }
 
+    #[tokio::test]
+    async fn test_cancel_request() {
```
Comment (tustvold) [inline src/messenger.rs:936]: I think this test would be easier to follow if the loops were broken up into separate functions, but it's fine as is also

File: src/messenger.rs [hunk 2]
```diff
@@ -922,6 +932,122 @@ mod tests {
...
+        // pause it after 3 bytes are sent by the client.
+        let (tx_front, rx_middle) = tokio::io::duplex(1);
+        let (tx_middle, mut rx_back) = tokio::io::duplex(1);
+
+        let messenger = Messenger::new(tx_front, 1_000);
+
+        let network_pause = Arc::new(Barrier::new(2));
+        let network_pause_captured = Arc::clone(&network_pause);
+        let handle_network = tokio::spawn(async move {
+            // Need to split both directions into read and write halfs so we can run full-deplux in two loops. Otherwise
```
Comment (tustvold) [inline src/messenger.rs:947]:
```suggestion
            // Need to split both directions into read and write halfs so we can run full-duplex in two loops. Otherwise
```

File: src/messenger.rs [hunk 3]
```diff
@@ -922,6 +932,122 @@ mod tests {
...
+    #[tokio::test]
+    async fn test_cancel_request() {
+        // Use a "virtual" network between a simulated broker and a client. The network is intercepted in the middle to
+        // pause it after 3 bytes are sent by the client.
+        let (tx_front, rx_middle) = tokio::io::duplex(1);
+        let (tx_middle, mut rx_back) = tokio::io::duplex(1);
+
+        let messenger = Messenger::new(tx_front, 1_000);
+
+        let network_pause = Arc::new(Barrier::new(2));
```
Comment (tustvold) [inline src/messenger.rs:944]: Perhaps an explanation of why 2?

File: src/messenger.rs [hunk 4]
```diff
@@ -922,6 +932,122 @@ mod tests {
...
+                .unwrap();
+        })
+        .fuse();
+
+        {
+            // cancel when we exit this block
+            pin_mut!(task_to_cancel);
+
+            // write exactly 3 bytes via the client and then cancel the task.
+            futures::select_biased! {
```
Comment (tustvold) [inline src/messenger.rs:1025]: I think this is racy, as network_pause.wait() could be reached allowing the network to continue and the task to finish, before this task is scheduled and exits the select block. I'm not sure that select_biased will prevent this, as even if network_pause triggers the wakeup, task_to_cancel will still be polled first

File: src/messenger.rs [hunk 5]
```diff
@@ -922,6 +932,122 @@ mod tests {
...
+            tokio::select! {
+                _ = direction1 => {}
+                _ = direction2 => {}
+            }
+        });
+
+        // simulated broker, just reads messages and answers w/ "api versions" responses
+        let handle_broker = tokio::spawn(async move {
+            for correlation_id in 0.. {
+                rx_back.read_message(1_000).await.unwrap();
```
Comment (tustvold) [inline src/messenger.rs:981]: Could possibly check that the message is an ApiVersions request

**Review by tustvold — APPROVED** [review]
Looks good to me, I think the test has a race, but otherwise :muscle:

File: src/messenger.rs (hunk 3 above)
Comment (crepererum) [reply src/messenger.rs:951]: done

File: src/messenger.rs (hunk 5 above)
Comment (crepererum) [reply src/messenger.rs]: done
